name: Deploy Next.js to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy with Serverless
        id: deploy
        run: |
          npx serverless deploy --stage prod > deploy.log
          cat deploy.log
          # Extract the URL from deployment output
          DEPLOY_URL=$(grep 'url:' deploy.log | awk '{print $2}')
          echo "App deployed at $DEPLOY_URL"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Output deployment URL
        run: echo "Your app is live at $DEPLOY_URL"
